apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: human-connection
  labels:
    human-connection.org/selector: deployment-human-connection-web
spec:
  ports:
    - name: web
      port: 3001
      targetPort: 3001
  selector:
    human-connection.org/selector: deployment-human-connection-web
